### PR TITLE
Avoid redundant computations in IRR calculation

### PR DESCRIPTION
**Pull request by jlopezpena**
The IRR computation adds and then subtract the previous iteration value before comparing to the tolerance. We can just compute the delta and compare that to the tolerance instead. This should also make the computation more robust if there is a large difference in magnitude between `x` and `delta`

### CODE REVIEW

**Review by Kai-Striega — COMMENTED** [review]
Good find! I'm going to do some digging on why it's failing the test - it should be an identical result.  I'm not quite sure where the errors are being introduced from.

**Comment by Kai-Striega** [comment]
> but this is all but guaranteed to give you numerical problems:

I agree, however, we went from that test passing to it failing. I'd like to investigate what those numerical problems are. Looking at the original issue https://github.com/numpy/numpy-financial/issues/15 it looks like it was an issue with the old irr solver, not with the most recent newton's method solver.

**Comment by Kai-Striega** [comment]
Yeah, the test currently tests that the IRR is equal to `-0.9999999990596069`. I don't believe this is the correct answer. Maybe it was introduced via numerical error?

**Comment by Kai-Striega** [comment]
Thanks for taking the time to investigate. I think we're getting somewhere. 

>  With the current algo, the floating point error on x - delta triggers the early exit, but the exit condition was not actually reached.

I see. Let's consider this a bug. 

> Actually, setting the guess to inflow / outflow - 1 seems to provide similar if not faster convergence in the positive case as well. 

Please give me some time to experiment with it myself, but, I like the idea. The current version seems to have some funny results at times, having a better guess could help with that.

> Is there a strong reason to keep the 0.1 default value?

When I rewrote IRR, I wanted to match what Google Sheets/Excel had. Is that a good reason? Probably not. We haven't made a release of this version of the IRR, so I'm happy to change it and get it right come release time.

**Comment by Kai-Striega** [comment]
```python
inflow = sum(x for x in values if x > 0)
outflow = -sum(x for x in values if x < 0)
guess = inflow / outflow - 1
```

I've played around with this a bit. It seems to work well for me too. Would you like to implement it and see if that helps as part of this PR?

I guess this could be tided up/optimised a bit by using NumPy functions, but I don't see this as being the bottleneck anyway. E.g. something like this (untested code)

```python
positive_cashflow = values > 0
inflow = values.sum(where=positive_cashflow)
outflow = values.sum(where=~positive_cashflow)
```

**Comment by Kai-Striega** [comment]
Sorry for taking so long to respond, I've been pretty bust lately – thank you for being patient.

I really like what I'm seeing here. The PR looks good, works in theory, and works in practice. In addition, the CI is green. 

> Perhaps it would be useful to have both implementations and let the user pass a computation method keyword to pick if the default doesn't seem to work?

I'm -0.5 on this. numpy-financial is on the cusp of not being maintained. I think this will add to the maintenance burden for any future contributors. In addition, it is supposed to support *simple* financial functions. So I think it will be fine to have only one method that works in the general case.

**Comment by Kai-Striega** [comment]
> Then my suggestion would be to use the denominator-free expression

I agree. I think the numerical stability trumps a minor performance gain.

Is there anything else you would like to add to this P.R.? I'm happy to merge.

**Comment by Kai-Striega** [comment]
Merged. Thanks @jlopezpena for taking the time to contribute

**Comment by user799595** [comment]
I worry about the logic that this PR adds for the initial guess.

Consider a bond with coupon rate `C`. Its cashflows are
```
values = [-1, C, C, C, C, ... (1+C)]
```
The IRR of the above is `C`.

But the formula for the initial guess approximates it as `NC` where `N` is the number of coupon dates. For large `N` this isn't a good guess.

See
https://github.com/numpy/numpy-financial/blob/fb63b045ab9e488b5d5d9acf6e0eacca6102e404/numpy_financial/_financial.py#L763

**Pull request merged**
