### PR TITLE
Remove assert_almost_equals from tests

### PR DESCRIPTION
**Pull request by ArCh12312**
#66 Fixed the issue
Changed assert_almost_equals to assert_allclose and a custom function(assert_decimal_close).
Had to create assert_decimal_close, which finds the absolute difference in values and compares it to a tolerance level.
Cannot use the `assert_allclose` because it uses isfinite under the covers which does not support the Decimal type.
See issue: https://github.com/numpy/numpy/issues/9954

### CODE REVIEW

**Review by Kai-Striega — APPROVED** [review]
There's one issue that's coming up in the CI:

`tests/test_financial.py:1:1: I001 [*] Import block is un-sorted or un-formatted`

But I don't see any changes you have made other than to delete a line. Either way, would you be able to fix it?

**Comment by ArCh12312** [comment]
Hey! I have sorted the import block and added the new line back.

**Comment by Kai-Striega** [comment]
Thanks, @ArCh12312, I've re-run the tests to make sure everything is ok. If it is, I'm glad to merge this.

**Comment by ArCh12312** [comment]
Hey @Kai-Striega, I have reformatted the file using the command `ruff format ./test_financial.py'. Please review it.

**Pull request closed without merging**
