### PR TITLE
Add automated documentation testing when building

### LINKED ISSUE #73: TST/CI: Automatically test documentation when it is built
### Proposed new feature or change:

The CI pipeline should automatically test the code examples in the documentation when it is being built. This will ensure that our documentation remains current.

### PR DESCRIPTION
**Pull request by MashyBasker**
The `--doctest-modules` option of pytest is added to the original `poetry run pytest` for testing the documentation code examples.

### CODE REVIEW

**Comment by Kai-Striega** [comment]
This looks good from your side (except the tests failing) would you be able to look at those within this PR?

**Comment by MashyBasker** [comment]
As I commented in [issue#95](https://github.com/numpy/numpy-financial/issues/95), we probably need to use `asser_allcose` instead `assert_almost_equal`.
 I saw someone was already working on a fix. I they aren't anymore, I would be happy to work on it.

**Comment by MashyBasker** [comment]
I just tried changing every `assert_almost_equal` to `assert_allclose`. But this breaks the other tests. I'll look into it more

**Comment by Kai-Striega** [comment]
I don't think that's the issue (here) I think it's just that we're comparing floating point numbers in the doctests which aren't _exactly_ equal. Could you try rounding the output of the examples to see if that fixes it?

**Comment by MashyBasker** [comment]
I have fixed the doctests and they now work fine in my local machine and my forked repository. The problems were mostly:

- rounding error
- `# may vary` comments in the output(should be provided in the function
- Empty lines in the output that should have `<BLANKLINE>` command.
- Incorrect raise exception output.

**Comment by MashyBasker** [comment]
@Kai-Striega I have fixed the linter problem in the `mirr` doctests

**Comment by Kai-Striega** [comment]
@MashyBasker thanks. It looks like some tests are still failing.

FYI you can run the style checks yourself on your local machine. See these lines:

https://github.com/numpy/numpy-financial/blob/db5ab0a7c4d55c92236718d2d35c204d56d8a13b/.github/workflows/lint.yml#L49-L53

**Comment by MashyBasker** [comment]
@Kai-Striega I made the changes and `ruff` works in my local machine perfectly too. Awaiting your feedback

**Comment by Kai-Striega** [comment]
There's still one line that's too long `numpy_financial/_financial.py:1071:89: E501 Line too long (91 > 88)` I'm not quite sure why your ruff installation didn't pick that up :(. 

Otherwise I think this looks really good and ready to go!

**Comment by MashyBasker** [comment]
I've addressed the line length issue in . Apologies for any oversight, and I appreciate your diligence in maintaining the style guide :)

**Comment by Kai-Striega** [comment]
@MashyBasker lint is green. Give me a few minutes to look through it again, but I think this should be good to go.

**Comment by MashyBasker** [comment]
Thanks. I'll use the guide next time

**Pull request merged**
