### PR TITLE
BLD: Attempt to build using spin

### PR DESCRIPTION
**Pull request by Kai-Striega**
This commit is the first commit to try and move from poetry to spin.

It is not working at the moment, namely the test runner cannot find the given tests.

### CODE REVIEW

**Comment by stefanv** [comment]
With these changes, it now builds and tests on my machine; I am running into some numpy 2.0 issues, so those will still have to be addressed separately.

**Comment by stefanv** [comment]
I see you're using ruff for linting. Providing a pre-commit hook would be helpful (or a custom hook, like SciPy, is fine too).

**Comment by stefanv** [comment]
Errors I see locally:

```
FAILED numpy_financial/tests/test_financial.py::TestNpv::test_fuzz - ValueError: Buffer dtype mismatch, expected 'const double' but got 'float'
FAILED numpy_financial/tests/test_financial.py::TestNpv::test_rate_of_negative_one_returns_nan[-1] - ValueError: Buffer dtype mismatch, expected 'const double' but got 'long'
FAILED numpy_financial/tests/test_financial.py::TestNpv::test_rate_of_negative_one_returns_nan[-1.0] - ValueError: Buffer dtype mismatch, expected 'const double' but got 'long'
FAILED numpy_financial/tests/test_financial.py::TestMirr::test_mirr[values0-0.08-0.055-0.0666] - ValueError: Buffer dtype mismatch, expected 'const double' but got 'long'
FAILED numpy_financial/tests/test_financial.py::TestMirr::test_mirr[values1-0.1-0.12-0.126094] - ValueError: Buffer dtype mismatch, expected 'const double' but got 'long'
FAILED numpy_financial/tests/test_financial.py::TestMirr::test_mirr[values2-0.05-0.06-0.3428] - ValueError: Buffer dtype mismatch, expected 'const double' but got 'long'
FAILED numpy_financial/tests/test_financial.py::TestIrr::test_npv_irr_congruence - ValueError: Buffer dtype mismatch, expected 'const double' but got 'long'
```

**Comment by Kai-Striega** [comment]
Thanks heaps for helping out. I think I can take it from here. I don't think those are NumPy 2.0 issues. They are just from me not having templated the Cython code fully yet. I'll take a look at it now

**Pull request merged**
