### PR TITLE
MAINT: Create the basic structure of the numpy_financial package.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
I tried to preserve the commit history of 'financial.py' and 'test_financial.py'.

I added a few standard files, including a very basic 'setup.py'.  It works well enough to install a package that passes the (updated) tests:

```
$ ~/mc37numpy/bin/pytest 
================================================== test session starts ===================================================
platform darwin -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /Users/warren/repos/git/forks/numpy-financial
collected 26 items                                                                                                       

test_financial.py ..........................                                                                       [100%]

=============================================== 26 passed in 0.13 seconds ================================================
```

There is a lot more basic configuration to do, but I'd like to verify that this initial structure looks good before proceeding.

Also, any Sphinx gurus, distutils gurus, CI gurus, PyPI gurus, etc., are encouraged to contribute pull requests so we can get this package into shape as quickly.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The numpy repository doesn't have an AUTHORS.txt either, so I don't think we need it.

The essential changes in `test_financial.py` fix the imports to use the `numpy_financial` library.  The rest of the changes are PEP 8 whitespace clean up.  In hindsight, those could have been made in separate commits, but when I started I didn't think the PEP 8 changes would be so significant.

**Comment by Kai-Striega** [comment]
That all sounds good. Do you want to keep this PR open and add CI/Docs/etc? If not, I'll run the tests when I get home tonight and confirm everything works as expected.

**Comment by WarrenWeckesser** [comment]
I'm fine with getting the package into shape through a series of pull requests, rather than trying to do it all in this one.  So separate PRs for docs and for CI, for example, would be fine.  I expect all the changes will be pretty straightforward, but I don't know the details of all the machinery well enough to get it all right in one PR.  I'll make an issue with a "to do" list.

**Comment by Kai-Striega** [comment]
:+1: I don't have write access to numpy, so I can't merge your PRs. I can do some work on CI/Docs this afternoon if you prefer to focus on something else.

**Comment by charris** [comment]
Should we add @Kai-Striega to the `numpy-financial` maintainers?

**Comment by Kai-Striega** [comment]
@WarrenWeckesser I've run the tests and they all pass on my machine and they all pass. As a follow-up question, in setup.py we're using NumPy's distutils, do we still need these or can we change to using only setuptools?

@charris I originally intended to only help set up / maintain as I'm concerned about being the main maintainer. Saying that, once set up, I suspect there won't be too much maintainance burden. I'll still be active within SciPy (and NumPy) - so the required maintanence should not be much more than I already intend to do.

**Comment by WarrenWeckesser** [comment]
I'm going to self-merge this, and I'll probably continue to be quick to merge changes until we have this in good enough shape to call it pre-release.

**Comment by WarrenWeckesser** [comment]
@charris asked

> Should we add @Kai-Striega to the numpy-financial maintainers?

Sure!

Kai, helping out now is not a commitment to become the permanent maintainer of the package.  You can drop your involvement with the package at any time.  Any help you can provide now during this transition phase is certainly appreciated!

**Comment by WarrenWeckesser** [comment]
I've started self-merging PRs to get the package set up reasonably quickly.

**Comment by charris** [comment]
> I've started self-merging PRs to get the package set up reasonably quickly.

That's fine. At some point the initial setup will be done and we can review the whole thing.

**Comment by Kai-Striega** [comment]
@charris @WarrenWeckesser. I'd be happy to be a maintainer. I've been working on this too, I'll try to get a few PRs in over the weekend.

**Comment by WarrenWeckesser** [comment]
Thanks, Kai.  As you can see, this PR has been merged.  I have a github workflow set up to run unit tests on PRs and on any push to the master branch (https://github.com/numpy/numpy-financial/blob/master/.github/workflows/pythonpackage.yml).  I've been trying to get another workflow set up to build the docs and push the result to the repo's gh-pages branch, which will be rendered at https://numpy.org/numpy-financial/.  What is there now is the result of a manual push of the docs.  I've been trying to get an automated workflow set up, but I'm still figuring out what's possible.  I am currently stuck at pushing the newly built docs back to the repo after they are built in a workflow.  There are authentication issues to be worked out.

**Comment by Kai-Striega** [comment]
I'll take a look at the authentication issues when I get home from work. Also, I could have been clearer, by "working on this" I meant numpy-financial at large, not this particular PR.

**Comment by WarrenWeckesser** [comment]
Yeah, that's what I understood. :smile:  This was just a convenient place to give an update.

**Comment by charris** [comment]
@Kai-Striega I sent you an invite.

**Pull request merged**
