### PR TITLE
Add further metadata to setup(...)

### PR DESCRIPTION
**Pull request by Kai-Striega**

### CODE REVIEW

**Comment by Kai-Striega** [comment]
@WarrenWeckesser just a quick question, I've set ``maintainer_email='numpy-discussion@python.org'``, this is the same as is given for NumPy. Do you think there is a more appropriate list? I don't think numpy-financial would receive sufficient traffic to warrant its own list - but the whole point of numpy-financial is to separate numpy / numpy-financial.

**Comment by WarrenWeckesser** [comment]
I think numpy-discussion is fine.  I don't expect much traffic.  If it ever becomes too much of a distraction on the main mailing list, we can figure out an alternative.

**Comment by WarrenWeckesser** [comment]
I'm not sure about the funding tags.    These functions are being removed from NumPy, and the numpy-financial library won't necessarily benefit from the funding provided to NumPy.  Let's take those references out.  (Any opinion on that, @rgommers?)  Otherwise, the changes look good.

**Comment by rgommers** [comment]
Agree with removing the funding tags.

**Comment by WarrenWeckesser** [comment]
Thanks Kai.  I rebased to fix the conflicts and pushed the changes to master.

**Comment by Kai-Striega** [comment]
@WarrenWeckesser thanks! Unfortunately I've had some things come up at work that I need to focus on. I'll try to keep active here as much as possible, but, work will need to take priority.

**Comment by WarrenWeckesser** [comment]
No problem, Kai.  Thanks for your help so far.

**Pull request closed without merging**
